# src/Blogger/BlogBundle/Resources/config/config.yml
parameters:
    # Blogger contact email address
    blogger_blog.emails.contact_email: kamrul.hasan@technovista.com.bd
    # Blogger max latest comments
    blogger_blog.comments.latest_comment_limit: 5